// Generated by StructFlattener v. 0.1.0
// Based on UnsafeStructs.in.cs
// Commandline: "..\..\tools\StructFlattener\bin\Debug\StructFlattener.exe" UnsafeStructs.in.cs -32 -out UnsafeStructs.x86.cs 
// CHANGES TO THIS FILE WILL BE LOST. Modify the input file, or improve StructFlattener if necessary. 
#if X86
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Runtime.InteropServices;
namespace ManagedNtApi.Unsafe
{
	[StructLayout ((LayoutKind)2, Pack = 1, Size = 8)]
	public unsafe struct UNICODE_STRING
	{
		[FieldOffset (0)]
		public ushort Length;
		[FieldOffset (2)]
		public ushort MaximumLength;
		[FieldOffset (4)]
		public char* buffer;
		public override string ToString ()
		{
			return Marshal.PtrToStringUni ((IntPtr)buffer);
		}
		unsafe ushort* Test {
			get {
				fixed (UNICODE_STRING* s = &this) {
					return &s->Length;
				}
			}
		}
	}
	// Based on wine's winnt.h, winternl.h definitions
	//struct _EXCEPTION_REGISTRATION_RECORD *ExceptionList;
	[StructLayout ((LayoutKind)2, Pack = 1, Size = 28)]
	public unsafe struct NT_TIB
	{
		[FieldOffset (0)]
		public IntPtr ExceptionList;
		[FieldOffset (4)]
		public IntPtr StackBase;
		[FieldOffset (8)]
		public IntPtr StackLimit;
		[FieldOffset (12)]
		public IntPtr SubSystemTib;
		[FieldOffset (16)]
		public IntPtr FiberData;
		[FieldOffset (16)]
		public int Version;
		[FieldOffset (20)]
		public IntPtr ArbitraryUserPointer;
		[FieldOffset (24)]
		public NT_TIB* Self;
	}
	[StructLayout (LayoutKind.Sequential)]
	public struct CLIENT_ID
	{
		public IntPtr /*HANDLE*/UniqueProcess;
		public IntPtr /*HANDLE*/UniqueThread;
	}
	[StructLayout (LayoutKind.Sequential)]
	public unsafe struct LIST_ENTRY
	{
		public LIST_ENTRY* Flink;
		public LIST_ENTRY* Blink;
	}
	[StructLayout (LayoutKind.Sequential)]
	public struct ACTIVATION_CONTEXT_STACK
	{
		public IntPtr ActiveFrame;
		/*RTL_ACTIVATION_CONTEXT_STACK_FRAME *ActiveFrame;*/public LIST_ENTRY FrameListCache;
		public uint Flags;
		public uint NextCookieSequenceNumber;
		public uint StackId;
		//this isn't included in the WINE version
	}
	public unsafe struct GDI_TEB_BATCH
	{
		public uint Offset;
		public IntPtr /*HANDLE*/HDC;
		public fixed uint Buffer[0x136];
	};

	// Based on wine's winnt.h, winternl.h definitions
	/***********************************************************************
  * TEB data structure
  *//* win32/win64 *//* 000/0000 *//* 01c/0038 *//* 020/0040 *//* 028/0050 *//* 02c/0058 *//* 030/0060 *//* 034/0068 *//* 038/006c *//* 03c/0070 *//* 040/0078 *//* 044/0080 *//* 0c0/0100 *//* 0c4/0108 *//* 0c8/010c *//* 0cc/0110 *//* 1a4/02c0 *//* 1a8/02c8 *///The addition of StackId to ACTIVATION_CONTEXT_STACK removes 4 of the spare bytes
	/* 1c0/02ec *//* 1d4/0300 *//* 1fc/0350 *//* 6dc/0838 *//* 6e0/0840 *//* 6e4/0848 *//* 6e8/0850 *//* 6f0/0860 *//* 6f4/0868 *//* 6f8/086c *//* 6fc/0870 *//* 700/0878 *//* (wine's winternl.h says "glDispachTable" - most likely a typo...) *//* 714/0890 *//* b74/1150 *//* bdc/1220 *//* be0/1228 *//* be4/1230 *//* be8/1238 *//* bec/1240 *//* bf0/1248 *//* bf4/1250 *//* bf8/1258 used by advapi32 *//* c00/1268 used by advapi32 *//* e0c/1478 *//* e10/1480 *//* f10/1680 *//* f18/1690 *//* f1c/1698 *//* f20/16a0 *//* f28/16b0 *//* f2c/16b8 *//* f6c/1738 *//* f70/1740 *//* f74/1744 *//* f78/1748 *//* f7c/1750 *//* f80/1758 *//* f84/1760 *//* f88/1768 *//* f94/1780 *//* f98/1788 *//* f9c/178c *//* fa0/1790 *//* fa4/1798 *//* fa8/17a0 *//* fac/17a8 *//* fb0/17b0 */
	#if X64
	    public fixed IntPtr                 unknown[2];                        /*     17b8 */
#endif
	/* fb4/17c8 */[StructLayout ((LayoutKind)2, Pack = 1, Size = 4024)]
	public unsafe struct TEB
	{
		[FieldOffset (0)]
		public IntPtr Tib_ExceptionList;
		public unsafe NT_TIB* Tib_Ref {
			get {
				fixed (TEB* __s = &this)
					return (NT_TIB*)&__s->Tib_ExceptionList;
			}
		}
		[FieldOffset (4)]
		public IntPtr Tib_StackBase;
		[FieldOffset (8)]
		public IntPtr Tib_StackLimit;
		[FieldOffset (12)]
		public IntPtr Tib_SubSystemTib;
		[FieldOffset (16)]
		public IntPtr Tib_FiberData;
		[FieldOffset (16)]
		public int Tib_Version;
		[FieldOffset (20)]
		public IntPtr Tib_ArbitraryUserPointer;
		[FieldOffset (24)]
		public NT_TIB* Tib_Self;
		[FieldOffset (28)]
		public IntPtr EnvironmentPointer;
		/*HANDLE*/[FieldOffset (32)]
		public IntPtr ClientId_UniqueProcess;
		public unsafe CLIENT_ID* ClientId_Ref {
			get {
				fixed (TEB* __s = &this)
					return (CLIENT_ID*)&__s->ClientId_UniqueProcess;
			}
		}
		/*HANDLE*/[FieldOffset (36)]
		public IntPtr ClientId_UniqueThread;
		[FieldOffset (40)]
		public IntPtr ActiveRpcHandle;
		[FieldOffset (44)]
		public IntPtr ThreadLocalStoragePointer;
		/*PPEB*/[FieldOffset (48)]
		public IntPtr Peb;
		[FieldOffset (52)]
		public uint LastErrorValue;
		[FieldOffset (56)]
		public uint CountOfOwnedCriticalSections;
		[FieldOffset (60)]
		public IntPtr CsrClientThread;
		[FieldOffset (64)]
		public IntPtr Win32ThreadInfo;
		[FieldOffset (68)]
		public fixed uint Win32ClientInfo[31];
		[FieldOffset (192)]
		public IntPtr WOW32Reserved;
		[FieldOffset (196)]
		public uint CurrentLocale;
		[FieldOffset (200)]
		public uint FpSoftwareStatusRegister;
		[FieldOffset (204)]
		public IntPtr SystemReserved1_Start;
		public unsafe IntPtr* SystemReserved1 {
			get {
				fixed (TEB* __s = &this)
					return (IntPtr*)&__s->SystemReserved1_Start;
			}
		}
		[FieldOffset (420)]
		public int ExceptionCode;
		[FieldOffset (424)]
		public IntPtr ActivationContextStack_ActiveFrame;
		public unsafe ACTIVATION_CONTEXT_STACK* ActivationContextStack_Ref {
			get {
				fixed (TEB* __s = &this)
					return (ACTIVATION_CONTEXT_STACK*)&__s->ActivationContextStack_ActiveFrame;
			}
		}
		[FieldOffset (428)]
		public LIST_ENTRY* ActivationContextStack_FrameListCache_Flink;
		[FieldOffset (432)]
		public LIST_ENTRY* ActivationContextStack_FrameListCache_Blink;
		[FieldOffset (436)]
		public uint ActivationContextStack_Flags;
		[FieldOffset (440)]
		public uint ActivationContextStack_NextCookieSequenceNumber;
		[FieldOffset (444)]
		public uint ActivationContextStack_StackId;
		[FieldOffset (448)]
		public fixed byte SpareBytes1[20];
		[FieldOffset (468)]
		public IntPtr SystemReserved2_Start;
		public unsafe IntPtr* SystemReserved2 {
			get {
				fixed (TEB* __s = &this)
					return (IntPtr*)&__s->SystemReserved2_Start;
			}
		}
		[FieldOffset (508)]
		public uint GdiTebBatch_Offset;
		public unsafe GDI_TEB_BATCH* GdiTebBatch_Ref {
			get {
				fixed (TEB* __s = &this)
					return (GDI_TEB_BATCH*)&__s->GdiTebBatch_Offset;
			}
		}
		/*HANDLE*/[FieldOffset (512)]
		public IntPtr GdiTebBatch_HDC;
		[FieldOffset (516)]
		public fixed uint GdiTebBatch_Buffer[0x136];
		/*HANDLE*/[FieldOffset (1756)]
		public IntPtr gdiRgn;
		/*HANDLE*/[FieldOffset (1760)]
		public IntPtr gdiPen;
		/*HANDLE*/[FieldOffset (1764)]
		public IntPtr gdiBrush;
		/*HANDLE*/[FieldOffset (1768)]
		public IntPtr RealClientId_UniqueProcess;
		public unsafe CLIENT_ID* RealClientId_Ref {
			get {
				fixed (TEB* __s = &this)
					return (CLIENT_ID*)&__s->RealClientId_UniqueProcess;
			}
		}
		/*HANDLE*/[FieldOffset (1772)]
		public IntPtr RealClientId_UniqueThread;
		/*HANDLE*/[FieldOffset (1776)]
		public IntPtr GdiCachedProcessHandle;
		[FieldOffset (1780)]
		public uint GdiClientPID;
		[FieldOffset (1784)]
		public uint GdiClientTID;
		[FieldOffset (1788)]
		public IntPtr GdiThreadLocaleInfo;
		[FieldOffset (1792)]
		public fixed uint UserReserved[5];
		[FieldOffset (1812)]
		public IntPtr glDispatchTable_Start;
		public unsafe IntPtr* glDispatchTable {
			get {
				fixed (TEB* __s = &this)
					return (IntPtr*)&__s->glDispatchTable_Start;
			}
		}
		[FieldOffset (2932)]
		public IntPtr glReserved1_Start;
		public unsafe IntPtr* glReserved1 {
			get {
				fixed (TEB* __s = &this)
					return (IntPtr*)&__s->glReserved1_Start;
			}
		}
		[FieldOffset (3036)]
		public IntPtr glReserved2;
		[FieldOffset (3040)]
		public IntPtr glSectionInfo;
		[FieldOffset (3044)]
		public IntPtr glSection;
		[FieldOffset (3048)]
		public IntPtr glTable;
		[FieldOffset (3052)]
		public IntPtr glCurrentRC;
		[FieldOffset (3056)]
		public IntPtr glContext;
		[FieldOffset (3060)]
		public uint LastStatusValue;
		[FieldOffset (3064)]
		public ushort StaticUnicodeString_Length;
		public unsafe UNICODE_STRING* StaticUnicodeString_Ref {
			get {
				fixed (TEB* __s = &this)
					return (UNICODE_STRING*)&__s->StaticUnicodeString_Length;
			}
		}
		[FieldOffset (3066)]
		public ushort StaticUnicodeString_MaximumLength;
		[FieldOffset (3068)]
		public char* StaticUnicodeString_buffer;
		[FieldOffset (3072)]
		public Char StaticUnicodeBuffer_Start;
		public unsafe Char* StaticUnicodeBuffer {
			get {
				fixed (TEB* __s = &this)
					return (Char*)&__s->StaticUnicodeBuffer_Start;
			}
		}
		[FieldOffset (3596)]
		public IntPtr DeallocationStack;
		[FieldOffset (3600)]
		public IntPtr TlsSlots_Start;
		public unsafe IntPtr* TlsSlots {
			get {
				fixed (TEB* __s = &this)
					return (IntPtr*)&__s->TlsSlots_Start;
			}
		}
		[FieldOffset (3856)]
		public LIST_ENTRY* TlsLinks_Flink;
		public unsafe LIST_ENTRY* TlsLinks_Ref {
			get {
				fixed (TEB* __s = &this)
					return (LIST_ENTRY*)&__s->TlsLinks_Flink;
			}
		}
		[FieldOffset (3860)]
		public LIST_ENTRY* TlsLinks_Blink;
		[FieldOffset (3864)]
		public IntPtr Vdm;
		[FieldOffset (3868)]
		public IntPtr ReservedForNtRpc;
		[FieldOffset (3872)]
		public IntPtr DbgSsReserved_Start;
		public unsafe IntPtr* DbgSsReserved {
			get {
				fixed (TEB* __s = &this)
					return (IntPtr*)&__s->DbgSsReserved_Start;
			}
		}
		[FieldOffset (3880)]
		public uint HardErrorDisabled;
		[FieldOffset (3884)]
		public IntPtr Instrumentation_Start;
		public unsafe IntPtr* Instrumentation {
			get {
				fixed (TEB* __s = &this)
					return (IntPtr*)&__s->Instrumentation_Start;
			}
		}
		[FieldOffset (3948)]
		public IntPtr WinSockData;
		[FieldOffset (3952)]
		public uint GdiBatchCount;
		[FieldOffset (3956)]
		public uint Spare2;
		[FieldOffset (3960)]
		public IntPtr Spare3;
		[FieldOffset (3964)]
		public IntPtr Spare4;
		[FieldOffset (3968)]
		public IntPtr ReservedForOle;
		[FieldOffset (3972)]
		public uint WaitingOnLoaderLock;
		[FieldOffset (3976)]
		public IntPtr Reserved5_Start;
		public unsafe IntPtr* Reserved5 {
			get {
				fixed (TEB* __s = &this)
					return (IntPtr*)&__s->Reserved5_Start;
			}
		}
		[FieldOffset (3988)]
		public IntPtr* TlsExpansionSlots;
		[FieldOffset (3992)]
		public uint ImpersonationLocale;
		[FieldOffset (3996)]
		public uint IsImpersonating;
		[FieldOffset (4000)]
		public IntPtr NlsCache;
		[FieldOffset (4004)]
		public IntPtr ShimData;
		[FieldOffset (4008)]
		public uint HeapVirtualAffinity;
		[FieldOffset (4012)]
		public IntPtr CurrentTransactionHandle;
		[FieldOffset (4016)]
		public IntPtr ActiveFrame;
		[FieldOffset (4020)]
		public IntPtr* FlsSlots;
	}
	public struct POINT
	{
		public int x, y;
	}
}

#endif
